## Data Attributes

1. Sepal Length in cm
2. Sepal width in cm
3. Petal width in cm
4. petal Length in cm

## Class

1. Iris Setosa
2. Iris Versicolor
3. Iris Virginica

Business case study: Predict the class of the Iris plant



In [134]:
#Import Libraries
import numpy as np
import pandas as pd
import scipy
import statsmodels.api as sm
import matplotlib.pyplot as plt
import sklearn.linear_model as LinearRegression
import seaborn as sns
sns.set()


In [135]:
# Import Iris dataset from Sklearn

from sklearn import datasets
iris = datasets.load_iris()

In [136]:
type(iris)

sklearn.utils.Bunch

In [137]:
x=iris.data
y = iris.target

In [138]:
from sklearn.model_selection import train_test_split
# scaled_inputs are inputs/independent variables
# targets are dependent variables
# test_size = 80/20 rule
#random_state can be any number
# suffix with test will be used to test the model and the suffix with train will be used to train the model
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.3, random_state = 365, stratify = y)

In [139]:
#gamma
from sklearn.svm import SVC
# gamma here can be adjusted inorder to optimize the accuracy and matrix like 1.0,2.0 so on
svc = SVC(kernel = 'rbf', gamma = 10.0)

In [140]:
svc.fit(x_train,y_train)

SVC(gamma=10.0)

In [141]:
y_predict = svc.predict(x_test)

In [142]:

from sklearn.metrics import confusion_matrix
cm_rbf = confusion_matrix(y_test,y_predict)
cm_rbf

array([[14,  0,  1],
       [ 0, 13,  2],
       [ 0,  1, 14]], dtype=int64)

In [143]:
svc.score(x_test,y_test)

0.9111111111111111

In [148]:
#Linear

svc = SVC(kernel = 'linear')
svc.fit(x_train,y_train)
y_predict = svc.predict(x_test)
cm_lr = confusion_matrix(y_test,y_predict)
cm_lr

array([[15,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 15]], dtype=int64)

In [149]:
svc.score(x_test,y_test)

0.9555555555555556

In [150]:
#Polynomial

svc = SVC(kernel = 'poly')
svc.fit(x_train,y_train)
y_predict = svc.predict(x_test)
cm_poly = confusion_matrix(y_test,y_predict)
cm_poly

array([[15,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 15]], dtype=int64)

In [151]:
svc.score(x_test,y_test)

0.9777777777777777

In [152]:
#Sigmoid
svc = SVC(kernel = 'sigmoid')
svc.fit(x_train,y_train)
y_predict = svc.predict(x_test)
cm_sig = confusion_matrix(y_test,y_predict)
cm_sig

array([[ 5,  0, 10],
       [11,  0,  4],
       [15,  0,  0]], dtype=int64)

In [153]:
svc.score(x_test,y_test)

0.1111111111111111

In [ ]:
# We have checked the SVM model using all four forms of kernal function. As the polynomial exibits high accuracy and and predicts most of the data correctly, we will go with polynomial